apiVersion: v1
kind: Namespace
metadata:
  name: ns-posthub-env--
  labels:
    name: ns-posthub-env--


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posthub--env--
  namespace: ui--posthub--env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posthub--env--
  template:
    metadata:
      labels:
         app: posthub--env--
    spec:
      containers:
        - name: posthub--env--
          image: __ImageTag__
          env:
            - name: MONGO_URI
              value: mongodb://posthub-mongo-service:27020/posthub
            - name: JWT_KEY
              valueFrom:
                secretkeyRef:
                   name: jwtsecret
                   key: JWTKEY
            - name: NATS_CLUSTER_ID
              value: posthubcluster
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-eventhub-service:4222'
          resources:
            requests:
               cpu: 250m
               memory: 350Mi
            limits:
              cpu: 1100m
              memory: 700Mi
          readinessProbe:
            httpGet:
              path: /api/posthub/healthcheck #defined in application
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - containerPort: 3000
