apiVersion: v1
kind: Namespace
metadata:
  name: ns-posthub-env--
  labels:
    name: ns-posthub-env--


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users--env--
  namespace: ui--posthub--env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users--env--
  template:
    metadata:
      labels:
         app: users--env--
    spec:
      containers:
        - name: users--env--
          image: __ImageTag__
          env:
            - name: MONGO_URI
              value: mongodb://users-mongo-service:27020/users
            - name: JWT_KEY
              valueFrom:
                secretkeyRef:
                   name: jwtsecret
                   key: JWTKEY
          resources:
            requests:
               cpu: 250m
               memory: 350Mi
            limits:
              cpu: 1100m
              memory: 700Mi
          readinessProbe:
            httpGet:
              path: /api/users/healthcheck #defined in application
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - containerPort: 3000
